website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import db, Employee, Department, AssignDesignation, Designation, Signatories, Leaves
from flask import session
from datetime import datetime
from sqlalchemy.orm import joinedload
from flask import request, jsonify
from datetime import datetime
from flask import request
from flask import redirect, url_for, render_template
from datetime import date
from .models import Employee




views = Blueprint('views', __name__)


@views.route('/')
def home():
    return render_template('home.html')

@views.route('/home_login', methods=['POST'])
def dummy_login():
    # Dummy login logic
    # For now, just set a session variable to indicate user is logged in
    session['logged_in'] = True
    # Redirect to the employee list page or wherever you want to redirect after login
    return redirect(url_for('views.render_employee_list'))

@views.route('/employee_list')
def render_employee_list():
    employees = Employee.query.all()
    return render_template("employee_list.html", employees=employees)

@views.route('/delete_employee/<int:employee_id>', methods=['POST'])
def delete_employee(employee_id):
    employee = Employee.query.get_or_404(employee_id)
    db.session.delete(employee)
    db.session.commit()
    return redirect(url_for('views.render_employee_list'))  

@views.route('/update_employee/<int:employee_id>', methods=['GET', 'POST'])
def update_employee(employee_id):
    employee = Employee.query.get_or_404(employee_id)
    departments = Department.query.all()
    designations = Designation.query.all()
    if request.method == 'POST':
        
        employee.firstname = request.form['firstname']
        employee.middlename = request.form['middlename']
        employee.lastname = request.form['lastname']
        employee.address_line = request.form['address_line']
        employee.brgy = request.form['brgy']
        employee.province = request.form['province']
        employee.country = request.form['country']
        employee.zipcode = request.form['zipcode']

        department_name = request.form['department']
        department = Department.query.filter_by(dept_name=department_name).first()
        if department is None:
            department = Department(dept_name=department_name)
            db.session.add(department)

        employee.department = department

        designation_name = request.form['designation']
        designation = Designation.query.filter_by(designation_name=designation_name).first()
        if designation is None:
            designation = Designation(designation_name=designation_name)
            db.session.add(designation)

        assign_designation = AssignDesignation(employee_type=request.form['employee_type'], status=request.form['status'], designation=designation)
        employee.assign_designation = [assign_designation]

        db.session.commit()
        return redirect(url_for('views.render_employee_list'))

    return render_template('update_employee.html', employee=employee, departments=departments, designations=designations)

@views.route('/add_employee', methods=['GET', 'POST'])
def add_employee():
    if request.method == 'POST':
        
        firstname = request.form['firstname']
        middlename = request.form['middlename']
        lastname = request.form['lastname']
        address_line = request.form['address_line']
        brgy = request.form['brgy']
        province = request.form['province']
        country = request.form['country']
        zipcode = request.form['zipcode']
        department_name = request.form['department']
        employee_type = request.form['employee_type']
        status = request.form['status']
        designation_name = request.form['designation']

        department = Department.query.filter_by(dept_name=department_name).first()
        if department is None:
            department = Department(dept_name=department_name)
            db.session.add(department)

        designation = Designation.query.filter_by(designation_name=designation_name).first()
        if designation is None:
            designation = Designation(designation_name=designation_name)
            db.session.add(designation)

        new_employee = Employee(
            
            firstname=firstname,
            middlename=middlename,
            lastname=lastname,
            address_line=address_line,
            brgy=brgy,
            province=province,
            country=country,
            zipcode=zipcode,
            department=department,
        )

        assign_designation = AssignDesignation(employee_type=employee_type, status=status, designation=designation)
        new_employee.assign_designation.append(assign_designation)

        db.session.add(new_employee)
        db.session.commit()
        
        return redirect(url_for('views.render_employee_list'))
    return render_template('add_employee.html')


@views.route('/logout')
def logout():
    # Clear session data to log out the user
    session.pop('logged_in', None)
    return redirect(url_for('views.home'))



@views.route('/update_signatory/<int:signatory_id>', methods=['GET', 'POST'])
def update_signatory(signatory_id):
    # Your update signatory logic here
    return render_template('update_signatory.html', signatory_id=signatory_id)


@views.route('/apply_leave/<int:employee_id>', methods=['GET', 'POST'])
def apply_leave(employee_id):
    if request.method == 'POST':
        # Extract form data
        leave_type = request.form['leave_type']
        start_date_str = request.form['start_date']
        end_date_str = request.form['end_date']

        # Parse date strings into datetime objects
        start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
        end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()
        
        # Set leave_status to "Pending"
        leave_status = "Pending"
        
        # Create a new leave record with the provided data
        new_leave = Leaves(employee_id=employee_id, start_leave=start_date, end_leave=end_date, 
                           leave_type=leave_type, status=leave_status)
        db.session.add(new_leave)
        db.session.commit()
        
        return redirect(url_for('views.leave_list'))  # Updated endpoint name
    else:
        # Render the form, passing the employee_id to the template
        return render_template("apply_leave.html", employee_id=employee_id)




@views.route('/apply_leave_html')
def apply_leave_html():
    # Render apply_leave.html template
    return render_template("apply_leave.html")

@views.route('/add_signatories', methods=['GET', 'POST'])
def add_signatory():
    if request.method == 'POST':
        # Handle form submission to add a new signatory
        # Extract form data and create a new signatory record
        firstname = request.form['firstname']
        middlename = request.form.get('middlename', '')  # Handle the possibility of middlename being empty
        lastname = request.form['lastname']
        email = request.form['email']
        highersuperior = request.form['highersuperior']
        department_name = request.form['department']
        designation_name = request.form['designation']
        employee_type = request.form['employee_type']
        status = request.form['status']

        # Fetch the associated employee
        employee = Employee.query.filter_by(firstname=firstname, middlename=middlename, lastname=lastname).first()

        # Assuming you have proper validation to ensure an employee is found

        # Create a new signatory record associated with the employee
        new_signatory = Signatories(
            employee_id=employee.employee_id,  # Associate the signatory with the employee
            highersuperior=highersuperior,
            status=status
        )

        # Add the new signatory to the database
        db.session.add(new_signatory)
        db.session.commit()

        # Redirect to the signatories list page after adding
        return redirect(url_for('views.signatories_list'))
    else:
        # Render the add_signatory template for GET request
        # Fetch the list of employees to pass to the template
        employees = Employee.query.all()
        return render_template("add_signatories.html", employees=employees)

    
def get_employee_id():
    # Example implementation: retrieve employee_id from session
    return session.get('employee_id')

@views.route('/leave_list')
def leave_list():
    # Fetch all leave applications from the database
    leaves = Leaves.query.all()
    # Fetch all employees from the database
    employees = Employee.query.all()
    return render_template("leave_list.html", leaves=leaves, employees=employees)


@views.route('/approve_leave/<int:leave_id>', methods=['POST'])
def approve_leave(leave_id):
    # Retrieve the leave request by leave_id
    leave = Leaves.query.get_or_404(leave_id)

    # Extract director's first name and last name from the form data
    director_first_name = request.form['director_first_name']
    director_last_name = request.form['director_last_name']

    # Find if the director exists and is authorized
    authorized_director = Employee.query \
        .join(AssignDesignation) \
        .join(Designation) \
        .filter(Employee.firstname == director_first_name,
                Employee.lastname == director_last_name,
                Designation.designation_name == 'Director') \
        .first()

    if authorized_director:
        # Director is authorized, update leave status to 'Approved'
        leave.status = 'Approved'  # Corrected to leave.status
        db.session.commit()

        return jsonify(message="Leave approved successfully."), 200
    else:
        # Director is not authorized, return an error message
        return jsonify({'error': 'Invalid director name. Please provide correct first name and last name of the director.'}), 400


    

website/templates/add_employee.html
<!-- add_employee.html -->
{% extends "base.html" %}
{% block title %}Add Employee{% endblock %}

{% block content %}
<h1><a href="{{ url_for('views.render_employee_list') }}" style="text-decoration: none; color: inherit;">Employee Management System</a></h1>
<h2>Add Employee</h2>
<div class="form-container">
    <form method="POST" action="{{ url_for('views.add_employee') }}">
        
        <div class="form-group">
            <label for="firstname">First Name:</label>
            <input type="text" class="form-control" id="firstname" name="firstname" required>
        </div>
        <div class="form-group">
            <label for="middlename">Middle Name:</label>
            <input type="text" class="form-control" id="middlename" name="middlename">
        </div>
        <div class="form-group">
            <label for="lastname">Last Name:</label>
            <input type="text" class="form-control" id="lastname" name="lastname" required>
        </div>
        <div class="form-group">
            <label for="address_line">Address Line:</label>
            <input type="text" class="form-control" id="address_line" name="address_line" required>
        </div>
        <div class="form-group">
            <label for="brgy">Barangay:</label>
            <input type="text" class="form-control" id="brgy" name="brgy" required>
        </div>
        <div class="form-group">
            <label for="province">Province:</label>
            <input type="text" class="form-control" id="province" name="province" required>
        </div>
        <div class="form-group">
            <label for="country">Country:</label>
            <input type="text" class="form-control" id="country" name="country" required>
        </div>
        <div class="form-group">
            <label for="zipcode">Zip Code:</label>
            <input type="text" class="form-control" id="zipcode" name="zipcode" required>
        </div>
        <div class="form-group">
            <label for="department">Department:</label>
            <select class="form-control" id="department" name="department">
                <option value="Information Technology Department">Information Technology Department</option>
                <option value="Data Science Department">Data Science Department</option>
                <option value="Computer Science Department">Computer Science Department</option>
                <option value="Information System Department">Information System Department</option>
            </select>
        </div>
        <div class="form-group">
            <label for="designation">Designation:</label>
            <select class="form-control" id="designation" name="designation">
                <option value="Director">Director</option>
                <option value="Manager">Manager</option>
                <option value="Team Leader">Team Leader</option>
                <option value="Team Member">Team Member</option>
            </select>
        </div>
        <div class="form-group">
            <label for="employee_type">Employee Type:</label>
            <select class="form-control" id="employee_type" name="employee_type">
                <option value="Full-time">Full-Time</option>
                <option value="Part-time">Part-Time</option>
                <option value="Temporary">Temporary</option>
                <option value="Dismissed">Dismissed</option>
            </select>
        </div>
        <div class="form-group">
            <label for="status">Status:</label>
            <select class="form-control" id="status" name="status">
                <option value="Active">Active</option>
                <option value="Resigned">Resigned</option>
                <option value="AWOL">AWOL</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Add Employee</button>
    </form>
</div>
{% endblock %}

website/templates/apply_leave.html
<!-- apply_leave.html -->
{% extends "base.html" %}
{% block title %}Apply for Leave{% endblock %}

{% block content %}
<div class="container addemp-h1-title">
<h1>Employee Leave Application</h1>
</div>
<div class="form-container">
    <form method="POST" action="{{ url_for('views.apply_leave', employee_id=employee_id) }}">
        <div class="form-group">
            <label for="employee_id">Employee ID:</label>
            <input type="text" id="employee_id" name="employee_id" value="{{ employee_id }}" readonly>
        </div>
        <div class="form-group">
            <label for="leave_type">Type of Leave:</label>
            <select id="leave_type" name="leave_type" required>
                <option value="Vacation">Vacation</option>
                <option value="Sick">Sick</option>
                <option value="Maternity">Maternity</option>
                <option value="Paternity">Paternity</option>
                <option value="Annual Leave">Annual Leave</option>
            </select>
        </div>
        <div class="form-group">
            <label for="start_date">Start Date:</label>
            <input type="date" id="start_date" name="start_date" min="2020-01-o1" max="2030-01-01" required>
        </div>
        <div class="form-group">
            <label for="end_date">End Date:</label>
            <input type="date" id="end_date" name="end_date" min="2020-01-o1" max="2030-01-01" required>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
</div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,200,0,0" rel="stylesheet">
</head>
<body>

    <nav class="navbar">
        
        <span id="menu-btn" class="material-symbols-outlined">menu</span>
    </nav>

    <!-- Side navigation menu -->
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{{ url_for('views.render_employee_list') }}">Employee List</a>
        <a href="{{ url_for('views.signatories_list') }}">Signatories List</a>
        <a href="{{ url_for('views.leave_list') }}">Leave List</a>
        <a href="{{ url_for('views.render_payroll_list') }}">Payroll</a>
        <a href="{{ url_for('views.logout') }}">Log out</a>
    </div>
    
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {% if display_footer %}
    <footer>
        <p>Event-Driven Programming - Milestone 2 | 4-313<br>By: Evanica Rose Juarbal, Shiloh Millondaga, Kristyle Marie Modin</p>
    </footer>
    {% endif %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("menu-btn").innerText = 'close'; // Change menu icon to close icon
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("menu-btn").innerText = 'menu'; // Change close icon back to menu icon
        }

        document.getElementById('menu-btn').onclick = function() {
            var navWidth = document.getElementById("mySidenav").style.width;
            if (navWidth === "250px" || navWidth === "") {
                closeNav();
            } else {
                openNav();
            }
        }
    </script>
    
    {% block javascript %}
    <script type="text/javascript">
        function deleteNote(noteId) {
            fetch("/delete-note", {
                method: "POST",
                body: JSON.stringify({ noteId: noteId }),
            }).then((_res) => {
                window.location.href = "/";
            });
        }
    </script>
    {% endblock %}
</body>
</html>

website/templates/check_payroll.html
<!-- check_payroll.html -->
{% extends "base.html" %}
{% block title %}Check Payroll{% endblock %}

{% block content %}
<div class="container">
    <h1>Payroll Information</h1>
    <hr>
    <div class="row">
        <div class="col-md-6">
            <h3>Employee Information</h3>
            <p><strong>Employee ID:</strong> {{ employee.employee_id }}</p>
            <p><strong>Full Name:</strong> {{ employee.firstname }} {{ employee.middlename }} {{ employee.lastname }}</p>
            <hr>
            <h3>Date Information</h3>
            <p><strong>Date Today:</strong> {{ date_today }}</p>
            <p><strong>Date Start:</strong> <input type="date" id="date_start" name="date_start"></p>
            <p><strong>Date End:</strong> <input type="date" id="date_end" name="date_end"></p>
        </div>
        <div class="col-md-6">
            <h3>Initial Income</h3>
            <p><strong>Designation:</strong>
                {% if employee.assign_designation %}
                {{ employee.assign_designation[0].designation.designation_name }}
                {% else %}
                    No designation assigned
                {% endif %}</p>
            <p>
            <strong>Employee Type:</strong>
            {% for assign_designation in employee.assign_designation %}
                {% set employee_type = assign_designation.employee_type %}
                {{ employee_type }}
            {% endfor %}
            </p>
            <p><strong>Initial Income:</strong> {{ initial_income }}</p>
            <p><strong>Tax Rate:</strong> {{ tax_rate }}</p>
            <hr>
            <h3>Calculated Payroll</h3>
            <p><strong>Net Income:</strong> <span id="net_income"></span></p>
            <p><strong>Additional Deductions:</strong> <span id="additionalDeductions"></span></p>
            <p><strong>Tax Deduction:</strong> <span id="tax_deduction"></span></p>

            
            <button onclick="calculatePayroll()">Generate Payslip</button>
        </div>
    </div>
</div>

<script>
function calculatePayroll() {
    var dateStart = document.getElementById("date_start").value;
    var dateEnd = document.getElementById("date_end").value;
    var initialIncome = parseFloat("{{ initial_income }}");
    
    // Calculate number of days between date start and date end
    var startDate = new Date(dateStart);
    var endDate = new Date(dateEnd);
    var daysWorked = (endDate - startDate) / (1000 * 60 * 60 * 24) + 1; // Including both start and end dates
    
    // Calculate total income before tax deduction
    var totalIncomeBeforeTax = initialIncome * daysWorked;
    
    // Calculate tax deduction based on total income
    var taxDeduction = totalIncomeBeforeTax * parseFloat("{{ tax_rate }}");
    
    // Calculate additional deductions based on employee type
    var additionalDeductions = 0;
    if ("{{ employee.assign_designation[0].employee_type }}" === 'Part-time') {
    additionalDeductions = (initialIncome * daysWorked) / 2;    
    }

    
    // Deduct additional deductions from total income before tax deduction
    var totalIncomeAfterDeductions = totalIncomeBeforeTax - additionalDeductions;
    
    // Deduct tax from total income after additional deductions
    var netIncome = totalIncomeAfterDeductions - taxDeduction;
    
    // Display calculated values
    document.getElementById("net_income").innerText = netIncome.toFixed(2);
    document.getElementById("tax_deduction").innerText = taxDeduction.toFixed(2);
    document.getElementById("additionalDeductions").innerText = additionalDeductions.toFixed(2);

    
}
</script>
{% endblock %}

website/templates/employee_list.html
<!-- employee_list.html -->
{% extends "base.html" %}
{% block title %}Employee List{% endblock %}

{% block content %}
<div class="container emp-h1-title"> 
    <h1>Employee Management System</h1>
</div>
<div class="emplist-tablewithbutton">
    <div class="table-container">
        <h2 class="emp-h2-title">Employee List</h2>
        <table>
            <thead>
                <tr>
                    <th>Employee ID </th>
                    <th>First Name</th>
                    <th>Middle Name</th>
                    <th>Last Name</th>
                    <th>Address Line</th>
                    <th>Barangay</th>
                    <th>Province</th>
                    <th>Country</th>
                    <th>Zip Code</th>
                    <th>Department</th>
                    <th>Designation</th>
                    <th>Employee Type</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td>{{ employee.employee_id }}</td>
                    <td>{{ employee.firstname }}</td>
                    <td>{{ employee.middlename }}</td>
                    <td>{{ employee.lastname }}</td>
                    <td>{{ employee.address_line }}</td>
                    <td>{{ employee.brgy }}</td>
                    <td>{{ employee.province }}</td>
                    <td>{{ employee.country }}</td>
                    <td>{{ employee.zipcode }}</td>
                    <td>{{ employee.department.dept_name }}</td>
                    <td>
                        {% if employee.assign_designation %}
                            {{ employee.assign_designation[0].designation.designation_name }}
                        {% else %}
                            No designation assigned
                        {% endif %}
                    </td>
                    <td>
                        {% for assign_designation in employee.assign_designation %}
                            {{ assign_designation.employee_type }}
                        {% endfor %}
                    </td>
                    <td>
                        {% for assign_designation in employee.assign_designation %}
                            {{ assign_designation.status }}
                        {% endfor %}
                    </td>
                    <td class="buttons">
                        <form method="POST" action="{{ url_for('views.delete_employee', employee_id=employee.employee_id) }}" style="display: inline;">
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                        <a href="{{ url_for('views.update_employee', employee_id=employee.employee_id) }}"><button class="btn btn-primary btn-sm">Update</button></a>                    
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="container mt-3">
        <a href="{{ url_for('views.add_employee') }}" class="btn btn-primary">Add Employee</a>
    </div>
</div>
{% endblock %}

{% set display_footer = True %} 

website/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <div class="container emp-h1-title">
    <h1>Welcome to the Employee Management System</h1>
    </div>
    <div class="form-container">
        <form method="POST" action="{{ url_for('views.dummy_login') }}">
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" class="form-control" required>
            </div>
            <div class="form-group">
                <p>Login as:</p>
                <input type="radio" id="signatories" name="login_type" value="signatories" required>
                <label for="signatories">Signatories</label>
                <input type="radio" id="employee" name="login_type" value="employee" required>
                <label for="employee">Employee</label>
            </div>
            <div class="button-home">
            <button type="submit" class="btn btn-primary">Login</button>
            </div>
        </form>
    </div>
</body>
</html>

website/templates/update_employee.html
<!--update_employee.html-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <title>Update Employee</title>
</head>
<body>
    <div class="container addemp-h1-title"> 
    <h1><a href="{{ url_for('views.render_employee_list') }}" style="text-decoration: none; color: inherit;">Employee Management System</a></h1>
    </div>
    <h2 class="emp-h2-title">Update Employee</h2>
    <div class="form-container">
    <form method="POST" action="{{ url_for('views.update_employee', employee_id=employee.employee_id) }}">
        <label for="firstname">First Name:</label>
        <input type="text" id="firstname" name="firstname" value="{{ employee.firstname }}">
        <label for="middlename">Middle Name:</label>
        <input type="text" id="middlename" name="middlename" value="{{ employee.middlename }}">
        <label for="lastname">Last Name:</label>
        <input type="text" id="lastname" name="lastname" value="{{ employee.lastname }}">
        <label for="address_line">Address Line:</label>
        <input type="text" id="address_line" name="address_line" value="{{ employee.address_line }}">
        <label for="brgy">Barangay:</label>
        <input type="text" id="brgy" name="brgy" value="{{ employee.brgy }}">
        <label for="province">Province:</label>
        <input type="text" id="province" name="province" value="{{ employee.province }}">
        <label for="country">Country:</label>
        <input type="text" id="country" name="country" value="{{ employee.country }}">
        <label for="zipcode">Zip Code:</label>
        <input type="text" id="zipcode" name="zipcode" value="{{ employee.zipcode }}">
        <div class="form-group">
            <label for="department">Department:</label>
            <select class="form-control" id="department" name="department">
                <option value="IT Department" {% if employee.department.dept_name == 'Information Technology Department' %} selected {% endif %}>Information Technology Department</option>
                <option value="DS Department" {% if employee.department.dept_name == 'Data Science Department' %} selected {% endif %}>Data Science Department</option>
                <option value="CS Department" {% if employee.department.dept_name == 'Computer Science Department' %} selected {% endif %}>Computer Science Department</option>
                <option value="IS Department" {% if employee.department.dept_name == 'Information System Department' %} selected {% endif %}>Information System Department</option>
            </select>
        </div>
        <div class="form-group">
            <label for="designation">Designation:</label>
            <select class="form-control" id="designation" name="designation">
                <option value="Director" {% if employee.assign_designation[0].designation.designation_name == 'Director' %} selected {% endif %}>Director</option>
                <option value="Manager" {% if employee.assign_designation[0].designation.designation_name == 'Manager' %} selected {% endif %}>Manager</option>
                <option value="Team Leader" {% if employee.assign_designation[0].designation.designation_name == 'Team Leader' %} selected {% endif %}>Team Leader</option>
                <option value="Team Member" {% if employee.assign_designation[0].designation.designation_name == 'Team Member' %} selected {% endif %}>Team Member</option>
            </select>
        </div>
        <div class="form-group">
            <label for="employee_type">Employee Type:</label>
            <select class="form-control" id="employee_type" name="employee_type">
                <option value="Full-time" {% if employee.assign_designation.employee_type == 'Full-time' %} selected {% endif %}>Full-Time</option>
                <option value="Part-time" {% if employee.assign_designation.employee_type == 'Part-time' %} selected {% endif %}>Part-Time</option>
                <option value="Temporary" {% if employee.assign_designation.employee_type == 'Temporary' %} selected {% endif %}>Temporary</option>
                <option value="Dismissed" {% if employee.assign_designation.employee_type == 'Dismissed' %} selected {% endif %}>Dismissed</option>

            </select>
        </div>
        <div class="form-group">
            <label for="status">Status:</label>
            <select class="form-control" id="status" name="status">
                <option value="Active" {% if employee.assign_designation.status == 'Active' %} selected {% endif %}>Active</option>
                <option value="Resigned" {% if employee.assign_designation.status == 'Resigned' %} selected {% endif %}>Resigned</option>
                <option value="AWOL" {% if employee.assign_designation.status == 'AWOL' %} selected {% endif %}>AWOL</option>
            </select>
        </div>
        
        <button type="submit" class="btn btn-primary">Update Employee</button>
    </form>
</body>
</html>